services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./www:/app/public
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php

  php:
    container_name: php
    image: php:fpm
    restart: unless-stopped
    volumes:
      - ./www:/app/public
      - ./php_config/php.ini:/usr/local/etc/php/php.ini
      - ./php_config/php.ini:/usr/local/etc/php/php.ini-development
      - ./php_config/php.ini:/usr/local/etc/php/php.ini-production
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    command: --max_allowed_packet=1024M
    environment:
      MARIADB_ROOT_PASSWORD: 48624862
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8123:80"
    environment:
      UPLOAD_LIMIT: 4G
      MEMORY_LIMIT: 4G
      PMA_USER: root
      PMA_PASSWORD: 48624862
      PMA_PORT: 3306

  ftp:
    container_name: ftp
    image: garethflowers/ftp-server
    restart: unless-stopped
    environment:
      FTP_USER: user
      FTP_PASS: user
    ports:
      - 20-21:20-21/tcp
      - 40000-40009:40000-40009/tcp
    volumes:
      - ./ftp_data:/home/user

  gundb:
    container_name: gundb
    image: gundb/gun
    restart: unless-stopped
    mem_limit: 256m
    ports:
      - "8765:8765"

volumes:
  caddy_data:
  caddy_config:

networks:
  default:
    name: web-server
